# Generated by Django 2.0.6 on 2018-06-16 18:31

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceType',
            fields=[
                ('attendance_value', models.FloatField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1.0)])),
                ('attendance_value_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('gender_title', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_title', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_name', models.CharField(max_length=200)),
                ('staff_shortname', models.CharField(max_length=100)),
                ('staff_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('staff_doj', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('staff_salary', models.PositiveIntegerField()),
                ('staff_gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainsite.Gender')),
                ('staff_job_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainsite.Job')),
            ],
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(verbose_name='Date')),
                ('staff_attendance_value', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.AttendanceType')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Staff')),
            ],
        ),
    ]
